import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const ICON={router:'◉',switch:'▦',server:'▣',device:'▱'};
const seed={nodes:[{id:'gw',name:'核心路由器',type:'router',x:470,y:220,ip:'10.0.0.1'},{id:'sw1',name:'交换机 A',type:'switch',x:250,y:370,ip:'10.0.1.1'},{id:'sw2',name:'交换机 B',type:'switch',x:690,y:370,ip:'10.0.2.1'},{id:'web',name:'Web Server',type:'server',x:100,y:520,ip:'10.0.1.10'},{id:'db',name:'Database',type:'server',x:400,y:550,ip:'10.0.1.20'},{id:'user',name:'办公终端',type:'device',x:820,y:530,ip:'10.0.2.22'}],edges:[['gw','sw1'],['gw','sw2'],['sw1','web'],['sw1','db'],['sw2','user']],regions:[{id:'rg-dc',name:'机房',members:['sw1','web','db'],collapsed:true,x:250,y:480},{id:'rg-office',name:'办公区',members:['sw2','user'],collapsed:false,x:0,y:0}]};
const load=()=>{try{const d=JSON.parse(localStorage.getItem('topology'));if(d&&d.nodes)return{regions:[],...d}}catch{}return seed};
function App(){const[data,setData]=useState(load);const[selected,setSelected]=useState('gw');const[selRegion,setSelRegion]=useState(null);const[tool,setTool]=useState('select');const[notice,setNotice]=useState('');const[drag,setDrag]=useState(null);const[draft,setDraft]=useState(null);const board=useRef();
useEffect(()=>localStorage.setItem('topology',JSON.stringify(data)),[data]);
const node=data.nodes.find(n=>n.id===selected)||data.nodes[0];const region=data.regions.find(r=>r.id===selRegion);
const updateNode=(k,v)=>setData(d=>({...d,nodes:d.nodes.map(n=>n.id===selected?{...n,[k]:v}:n)}));
const updateRegion=(k,v)=>setData(d=>({...d,regions:d.regions.map(r=>r.id===selRegion?{...r,[k]:v}:r)}));
const collapsedOf=id=>data.regions.find(r=>r.collapsed&&r.members.includes(id));
const posOf=id=>{const r=collapsedOf(id);if(r)return{x:r.x,y:r.y};const n=data.nodes.find(x=>x.id===id);return n?{x:n.x,y:n.y}:null};
const pick=id=>{setSelected(id);setSelRegion(null)};const pickRegion=id=>{setSelRegion(id);setSelected(null)};
const addNode=()=>{const id='node'+Date.now();const n={id,name:'新设备',type:'device',x:500,y:300,ip:'192.168.0.10'};setData(d=>({...d,nodes:[...d.nodes,n]}));pick(id);setTool('select');setNotice('已添加设备')};
const connect=()=>{if(!selected)return;const other=prompt('输入要连接的设备 ID（例如 sw1）');if(other&&data.nodes.some(n=>n.id===other)&&other!==selected&&!data.edges.some(e=>(e[0]===selected&&e[1]===other)||(e[1]===selected&&e[0]===other))){setData(d=>({...d,edges:[...d.edges,[selected,other]]}));setNotice('连接已创建')}};
const remove=()=>{setData(d=>({...d,nodes:d.nodes.filter(n=>n.id!==selected),edges:d.edges.filter(e=>!e.includes(selected)),regions:d.regions.map(r=>({...r,members:r.members.filter(m=>m!==selected)}))}));setSelected(data.nodes.find(n=>n.id!==selected)?.id);setNotice('设备已删除')};
const save=()=>setNotice('拓扑图已保存');
const exportJson=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='network-topology.json';a.click();setNotice('JSON 已导出')};
const validate=()=>{const linked=new Set(data.edges.flat());const isolated=data.nodes.filter(n=>!linked.has(n.id));setNotice(isolated.length?`发现 ${isolated.length} 个孤立节点`:'拓扑检查通过：没有孤立节点')};
const openDraft=()=>{setDraft({name:'',picks:[]});setTool('select')};
const togglePick=id=>setDraft(d=>({...d,picks:d.picks.includes(id)?d.picks.filter(p=>p!==id):[...d.picks,id]}));
const createRegion=()=>{const taken={};data.regions.forEach(r=>r.members.forEach(m=>taken[m]=r.name));const ok=[],skipped=[];draft.picks.forEach(id=>(taken[id]?skipped:ok).push(id));
if(!ok.length){setNotice(skipped.length?`未创建区域：${skipped.map(id=>data.nodes.find(n=>n.id===id)?.name).join('、')} 已在其他区域中`:'请先勾选至少一台成员设备');return}
const name=draft.name.trim()||'新区域';const ms=data.nodes.filter(n=>ok.includes(n.id));const cx=ms.reduce((s,n)=>s+n.x,0)/ms.length,cy=ms.reduce((s,n)=>s+n.y,0)/ms.length;const r={id:'region'+Date.now(),name,members:ok,collapsed:false,x:cx,y:cy};
setData(d=>({...d,regions:[...d.regions,r]}));setDraft(null);setSelRegion(r.id);setSelected(null);
setNotice(skipped.length?`区域「${name}」已创建；跳过 ${skipped.length} 台：${skipped.map(id=>`${data.nodes.find(x=>x.id===id)?.name}（已在「${taken[id]}」）`).join('、')}`:`区域「${name}」已创建，含 ${ok.length} 台设备`)};
const collapse=id=>setData(d=>{const g=d.regions.find(r=>r.id===id);const ms=d.nodes.filter(n=>g.members.includes(n.id));if(!ms.length)return d;const cx=ms.reduce((s,n)=>s+n.x,0)/ms.length,cy=ms.reduce((s,n)=>s+n.y,0)/ms.length;return{...d,regions:d.regions.map(r=>r.id===id?{...r,collapsed:true,x:cx,y:cy}:r)}});
const expand=id=>setData(d=>({...d,regions:d.regions.map(r=>r.id===id?{...r,collapsed:false}:r)}));
const dissolve=id=>{setData(d=>({...d,regions:d.regions.filter(r=>r.id!==id)}));if(selRegion===id)setSelRegion(null);setNotice('区域已解散，设备与连线均保留')};
const move=e=>{if(!drag)return;const r=board.current.getBoundingClientRect();
if(drag.kind==='node'){setData(d=>({...d,nodes:d.nodes.map(n=>n.id===drag.id?{...n,x:Math.max(35,e.clientX-r.left),y:Math.max(35,e.clientY-r.top)}:n)}));return}
const g=data.regions.find(x=>x.id===drag.id);if(!g)return;let dx=e.clientX-drag.px,dy=e.clientY-drag.py;
data.nodes.forEach(n=>{if(g.members.includes(n.id)){if(n.x+dx<35)dx=35-n.x;if(n.y+dy<35)dy=35-n.y}});
setDrag({...drag,px:e.clientX,py:e.clientY});
setData(d=>({...d,regions:d.regions.map(x=>x.id===drag.id?{...x,x:x.x+dx,y:x.y+dy}:x),nodes:d.nodes.map(n=>g.members.includes(n.id)?{...n,x:n.x+dx,y:n.y+dy}:n)}))};
return <div className="app"><header><div className="brand"><span className="brand-mark">⌁</span><div><strong>NETSCAPE</strong><small>TOPOLOGY STUDIO</small></div></div><div className="file"><span className="dot"></span><div><strong>office-network.json</strong><small>最近保存：刚刚</small></div></div><div className="top-actions"><button onClick={validate}>✓ 检查</button><button onClick={exportJson}>↓ 导出</button><button className="save" onClick={save}>保存更改</button></div></header>
<div className="toolbar"><div className="tool-group"><span>工具</span><button className={tool==='select'?'on':''} onClick={()=>setTool('select')}>↖ 选择</button><button className={tool==='connect'?'on':''} onClick={()=>{setTool('connect');connect()}}>⌁ 连接</button><button onClick={addNode}>＋ 设备</button><button onClick={openDraft}>▣ 区域</button></div><div className="tool-group zoom"><button>−</button><span>100%</span><button>＋</button><button onClick={()=>setNotice('画布已居中')}>⌗</button></div></div>
<div className="workspace"><aside className="inventory"><div className="section-title"><span>设备库</span><small>{data.nodes.length} 个节点</small></div><div className="device-types">{[['router','◉','路由器'],['switch','▦','交换机'],['server','▣','服务器'],['device','▱','终端设备']].map(([t,i,l])=><button onClick={()=>{const id='node'+Date.now();setData(d=>({...d,nodes:[...d.nodes,{id,name:l,type:t,x:500,y:320,ip:'192.168.0.2'}]}));pick(id)}} key={t}><i className={t}>{i}</i>{l}<span>＋</span></button>)}</div><div className="section-title nodes-head"><span>图中节点</span><small>点击查看</small></div><div className="node-list">{data.nodes.map(n=><button className={selected===n.id?'sel':''} onClick={()=>pick(n.id)} key={n.id}><i className={n.type}>{ICON[n.type]}</i><span><strong>{n.name}</strong><small>{n.ip}</small></span><b>›</b></button>)}</div><div className="section-title nodes-head"><span>区域</span><small>{data.regions.length} 个</small></div><div className="node-list">{data.regions.map(g=><button className={selRegion===g.id?'sel':''} onClick={()=>pickRegion(g.id)} key={g.id}><i className="region-ic">▤</i><span><strong>{g.name}</strong><small>{g.members.length} 台 · {g.collapsed?'已收起':'已展开'}</small></span><b>›</b></button>)}{!data.regions.length&&<p className="empty">还没有区域，点工具栏「▣ 区域」新建</p>}</div></aside>
<section className="canvas-wrap"><div className="canvas" ref={board} onMouseMove={move} onMouseUp={()=>setDrag(null)}>
{data.regions.filter(g=>!g.collapsed).map(g=>{const ms=data.nodes.filter(n=>g.members.includes(n.id));if(!ms.length)return null;const x0=Math.min(...ms.map(n=>n.x))-72,x1=Math.max(...ms.map(n=>n.x))+72,y0=Math.min(...ms.map(n=>n.y))-62,y1=Math.max(...ms.map(n=>n.y))+62;return <div className="region-box" key={g.id} style={{left:x0,top:y0,width:x1-x0,height:y1-y0}}><div className="region-tag"><button onClick={()=>pickRegion(g.id)}>▤ {g.name} · {ms.length} 台</button><button onClick={()=>collapse(g.id)}>收起 ▾</button></div></div>})}
{data.edges.map(([a,b],i)=>{const ra=collapsedOf(a),rb=collapsedOf(b);if(ra&&rb&&ra.id===rb.id)return null;const p1=posOf(a),p2=posOf(b);if(!p1||!p2)return null;const dx=p2.x-p1.x,dy=p2.y-p1.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return <div className={'edge'+((ra||rb)?' ext':'')} key={i} style={{left:p1.x,top:p1.y,width:len,transform:`rotate(${ang}deg)`}}><span></span></div>})}
{data.nodes.filter(n=>!collapsedOf(n.id)).map(n=><button className={'node '+n.type+(selected===n.id?' picked':'')} style={{left:n.x-42,top:n.y-31}} onMouseDown={e=>{e.stopPropagation();pick(n.id);setDrag({kind:'node',id:n.id})}} onClick={()=>pick(n.id)} key={n.id}><i>{ICON[n.type]}</i><strong>{n.name}</strong><small>{n.ip}</small></button>)}
{data.regions.filter(g=>g.collapsed).map(g=><div className={'region-card'+(selRegion===g.id?' picked':'')} style={{left:g.x-75,top:g.y-34}} onMouseDown={e=>{e.stopPropagation();pickRegion(g.id);setDrag({kind:'region',id:g.id,px:e.clientX,py:e.clientY})}} onDoubleClick={()=>expand(g.id)} onClick={()=>pickRegion(g.id)} key={g.id}><i>▤</i><strong>{g.name}</strong><small>{g.members.length} 台设备 · 已收起</small><button className="expand" onMouseDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();expand(g.id)}}>展开 ▸</button></div>)}
<div className="legend"><span><i className="router"></i>路由器</span><span><i className="switch"></i>交换机</span><span><i className="server"></i>服务器</span></div></div><div className="canvas-footer"><span>拖动节点或区域卡片调整位置 · {data.edges.length} 条连接 · {data.regions.length} 个区域</span><span>坐标系：画布局部</span></div></section>
<aside className="inspector"><div className="section-title"><span>{region?'区域属性':'属性'}</span><small>{region?'region':node?.type}</small></div>{region?<><label>区域名称<input value={region.name} onChange={e=>updateRegion('name',e.target.value)}/></label><div className="inspector-actions"><button onClick={()=>region.collapsed?expand(region.id):collapse(region.id)}>{region.collapsed?'▸ 展开区域':'▾ 收起区域'}</button><button className="danger" onClick={()=>dissolve(region.id)}>解散区域</button></div><div className="connections"><div className="section-title"><span>成员设备</span><small>{region.members.length} 台</small></div>{region.members.map(id=>{const n=data.nodes.find(x=>x.id===id);if(!n)return null;return <div className="connection" key={id}><span className={'mini '+n.type}></span><strong>{n.name}</strong><small>{n.ip}</small></div>})}</div><p className="hint">收起后成员隐藏为卡片，对外连线保留；解散只取消编组，设备与连线都保留。</p></>:node?<><label>设备名称<input value={node.name} onChange={e=>updateNode('name',e.target.value)}/></label><label>IP 地址<input value={node.ip} onChange={e=>updateNode('ip',e.target.value)}/></label><label>设备类型<select value={node.type} onChange={e=>updateNode('type',e.target.value)}><option value="router">路由器</option><option value="switch">交换机</option><option value="server">服务器</option><option value="device">终端设备</option></select></label><div className="inspector-actions"><button onClick={connect}>⌁ 添加连接</button><button className="danger" onClick={remove}>删除设备</button></div><div className="connections"><div className="section-title"><span>连接</span><small>{data.edges.filter(e=>e.includes(node.id)).length} 条</small></div>{data.edges.filter(e=>e.includes(node.id)).map((e,i)=>{const other=data.nodes.find(n=>n.id===(e[0]===node.id?e[1]:e[0]));return <div className="connection" key={i}><span className={'mini '+other?.type}></span><strong>{other?.name}</strong><small>在线</small></div>})}</div></>:<p>选择一个设备</p>}</aside></div>
{draft&&<div className="modal-mask" onClick={()=>setDraft(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="section-title"><span>新建区域</span><small>勾选成员设备</small></div><label>区域名称<input autoFocus value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="例如：办公区 / 机房"/></label><div className="pick-list">{data.nodes.map(n=>{const owner=data.regions.find(r=>r.members.includes(n.id));const on=draft.picks.includes(n.id);return <label className={'pick'+(on?' on':'')} key={n.id}><input type="checkbox" checked={on} onChange={()=>togglePick(n.id)}/><i className={n.type}>{ICON[n.type]}</i><span><strong>{n.name}</strong><small>{n.ip}</small></span>{owner&&<em>已在「{owner.name}」</em>}</label>})}</div><p className="hint">同一设备只能属于一个区域，已在其他区域的设备会被跳过并提示。</p><div className="modal-actions"><button onClick={()=>setDraft(null)}>取消</button><button className="save" onClick={createRegion}>创建区域（{draft.picks.length}）</button></div></div></div>}
{notice&&<div className="toast">{notice}</div>}</div>};createRoot(document.getElementById('root')).render(<App/>);
